version: "3.9"                      

services:       
  app:                              
    build: .
    container_name: api_solvd_employee_leave_management      
    restart: always
    ports:
      - "8080:8080"                                  
    volumes:
      - .:/usr/app
    env_file:
      - .env                
    links:
      - database                     
    depends_on:
      - database 

  database:                         
    image: postgres                 
    container_name: database_solvd_employee_leave_management
    restart: always                 
    ports:
      - "5432:5432"      
    environment:                 
      - POSTGRES_USER=postgres        
      - POSTGRES_PASSWORD=docker   
      - POSTGRES_DB=dbdocker         
    volumes:                        
      - pgdata:/data/postgres          
          
volumes:                         
  pgdata:                     
    driver: local                   