name: Continuous integration

on:
  push:
    paths:
      - "**.js"
      - "**.json"
      - "**.yml"
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  container-job:
    runs-on: ubuntu-latest
    
    container: macmiller87/solvd-employee-leave-management
    services:
      database:
        image: postgres
        env:     
          POSTGRES_USER: ${{ vars.POSTGRES_USER_DOCKER }}       
          POSTGRES_PASSWORD: ${{ vars.POSTGRES_PASSWORD_DOCKER }}  
          POSTGRES_DB: ${{ vars.POSTGRES_DATABASE_DOCKER }}
  
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.15.0

      - name: Install dependencies
        run: yarn install
    
      - name: Connect to PostgreSQL
        run: node ./src/database/service/postgService.js
        env:
          POSTGRES_USER: ${{ vars.POSTGRES_USER_DOCKER }}       
          POSTGRES_PASSWORD: ${{ vars.POSTGRES_PASSWORD_DOCKER }}  
          POSTGRES_DB: ${{ vars.POSTGRES_DATABASE_DOCKER }}
          POSTGRES_HOST_DOCKER: ${{ vars.POSTGRES_HOST_DOCKER }}
          POSTGRES_PORT: 5432
          SERVER_HOST: ${{ vars.SERVER_HOST }}
          SERVER_PORT: ${{ vars.SERVER_PORT }}
          SECRET_TOKEN: ${{ secrets.SECRET_TOKEN }}
          LOCALE: ${{ vars.LOCALE }}
      
      - name: Run Tests
        run: npm run test:github:actions
        env:
          POSTGRES_USER: ${{ vars.POSTGRES_USER_DOCKER }}       
          POSTGRES_PASSWORD: ${{ vars.POSTGRES_PASSWORD_DOCKER }}  
          POSTGRES_DB: ${{ vars.POSTGRES_DATABASE_DOCKER }}
          POSTGRES_HOST_DOCKER: ${{ vars.POSTGRES_HOST_DOCKER }}
          POSTGRES_PORT: 5432
          SERVER_HOST: ${{ vars.SERVER_HOST }}
          SERVER_PORT: ${{ vars.SERVER_PORT }}
          SECRET_TOKEN: ${{ secrets.SECRET_TOKEN }}
          LOCALE: ${{ vars.LOCALE }}







