name: Continuous integration

on:
  push:
    paths:
      - "**.js"
      - "**.json"
      - "**.yml"
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.15.0

    - run: yarn install
    - run: docker compose up
    - run: npm run test:github:actions
        

